/**
 * FIT 2 — calibration of the model's self-reported weight.
 *
 * This file is regenerated by `npm run fit:calibrate`, which runs the live
 * Gemini path over a sample of synthetic transactions with known ground truth
 * and fits an isotonic map from "what the model said" to "how often it was
 * right". Until that has been run against a real key, `CALIBRATION` is null and
 * the raw weight passes through unchanged — clearly labelled as uncalibrated
 * everywhere it is surfaced, rather than quietly pretending to be corrected.
 *
 * The reason this exists: a language model's stated confidence is a claim about
 * itself, and there is no reason to take it at face value. Fitting it against
 * outcomes turns an assertion into a measurement.
 */

export interface IsotonicPoint {
  x: number;
  y: number;
}

export interface CalibrationModel {
  generatedAt: string;
  model: string;
  /** Number of live API calls the fit is based on. */
  n: number;
  /** Isotonic map from raw stated weight (-1..1) to calibrated weight (-1..1). */
  points: IsotonicPoint[];
  metrics: {
    rawBrier: number;
    calibratedBrier: number;
    rawEce: number;
    calibratedEce: number;
    rawAccuracy: number;
    calibratedAccuracy: number;
  };
  /** Plain-English account of what the fit corrected. Written by the fit script. */
  summary: string;
  /** Per-archetype raw-vs-truth means, so over/under-confidence is visible. */
  byArchetype: { archetype: string; n: number; meanRaw: number; observed: number }[];
}

export const CALIBRATION: CalibrationModel | null = null;

function applyIsotonic(points: IsotonicPoint[], x: number): number {
  if (points.length === 0) return x;
  if (x <= points[0].x) return points[0].y;
  if (x >= points[points.length - 1].x) return points[points.length - 1].y;
  for (let i = 0; i < points.length - 1; i += 1) {
    const a = points[i];
    const b = points[i + 1];
    if (x >= a.x && x <= b.x) {
      if (b.x === a.x) return b.y;
      return a.y + ((x - a.x) / (b.x - a.x)) * (b.y - a.y);
    }
  }
  return points[points.length - 1].y;
}

export interface CalibrationOutcome {
  raw: number;
  calibrated: number;
  /** True when a fitted model was applied; false when the raw value passed through. */
  fitted: boolean;
  /** One line, for the UI. Always says what actually happened. */
  note: string;
}

export function calibrateWeight(raw: number): CalibrationOutcome {
  const bounded = Math.max(-1, Math.min(1, raw));
  if (!CALIBRATION) {
    return {
      raw: bounded,
      calibrated: bounded,
      fitted: false,
      note: "Uncalibrated — no fit has been run against a live model yet, so the raw stated weight is used as-is.",
    };
  }
  const calibrated = Math.max(-1, Math.min(1, applyIsotonic(CALIBRATION.points, bounded)));
  const delta = calibrated - bounded;
  const direction =
    Math.abs(delta) < 0.02
      ? "left effectively unchanged"
      : delta < 0
        ? `pulled down by ${Math.abs(delta).toFixed(2)} — the model was over-confident at this level`
        : `raised by ${delta.toFixed(2)} — the model was under-confident at this level`;
  return {
    raw: bounded,
    calibrated,
    fitted: true,
    note: `Stated ${bounded.toFixed(2)}, ${direction}, against ${CALIBRATION.n} outcomes with known ground truth.`,
  };
}
